# -*- coding: utf-8 -*-
"""MIR_HF_Inception.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AMXfJMGww1B5ITF4qk1s7Y9UjM5mDT4B
"""

import os
import glob
import matplotlib.pyplot as plt
import cv2
import random
import numpy as np
import pickle
from mpl_toolkits.axes_grid1 import ImageGrid
import pathlib
import pandas as pd



import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow import keras
from tensorflow.keras import layers
from keras.applications.inception_v3 import InceptionV3, preprocess_input
from keras.models import Sequential
from keras.layers import GlobalAveragePooling2D
from tensorflow.keras.layers import Dense, Dropout

! pip install kaggle


! mkdir ~/.kaggle



! cp kaggle.json ~/.kaggle/



! chmod 600 ~/.kaggle/kaggle.json

! kaggle datasets download -d shawngano/gano-cat-breed-image-collection

! unzip gano-cat-breed-image-collection.zip

PATH = '/content/Gano-Cat-Breeds-V1_1'

def make_dataFrame(data):
    path=pathlib.Path(data)
    filepaths=list(path.glob(r"*/*.jpg"))
    labels=list(map(lambda x: os.path.split(os.path.split(x)[0])[1],filepaths))
    d1=pd.Series(filepaths,name='filepaths').astype(str)
    d2=pd.Series(labels,name='labels')
    df=pd.concat([d1,d2],axis=1)
    return df

dataFrame = make_dataFrame(PATH)
dataFrame

class_names = dataFrame['labels'].unique()
class_names

fig, axes = plt.subplots(nrows=4, ncols=4, figsize=(12,10))
for i,ax in enumerate(axes.flat):
    idx = np.random.randint(1,5624)
    x = plt.imread(dataFrame.iloc[idx]['filepaths'])
    ax.imshow(x)
    ax.set_title(dataFrame['labels'][idx], fontsize=18)
    ax.set_axis_off()
plt.show()

dataFrame.labels.value_counts()

train_ratio = 0.75
test_ratio = 0.25

train, test = train_test_split(dataFrame, test_size = test_ratio, shuffle = True )

train_data_generator=ImageDataGenerator(
    rescale = 1./255,
    horizontal_flip=True,
    rotation_range=20,
    width_shift_range=.2,
    height_shift_range=.2,
    zoom_range=.2,
    shear_range=.2,
    fill_mode="nearest",
    validation_split=.2)

test_data_generator = ImageDataGenerator(rescale = 1./255)

BATCH_SIZE = 128
IMG_SIZE = (299, 299)

train_generator = train_data_generator.flow_from_dataframe(
    dataframe = train,
    x_col = "filepaths",
    y_col = "labels",
    target_size = IMG_SIZE,
    batch_size = BATCH_SIZE,
    class_mode = "categorical",
    subset = 'training',
    color_mode='rgb',
    shuffle = True,
    seed = 22
)

valid_generator = train_data_generator.flow_from_dataframe(
    dataframe = train,
    x_col = "filepaths",
    y_col = "labels",
    target_size = IMG_SIZE,
    batch_size = BATCH_SIZE,
    class_mode = "categorical",
    subset = 'validation',
    color_mode='rgb',
    shuffle = True,
    seed = 22
)

test_generator = test_data_generator.flow_from_dataframe(
    dataframe = test,
    x_col = "filepaths",
    target_size = IMG_SIZE,
    batch_size = 1,
    color_mode='rgb',
    class_mode = None,
    shuffle = False
)

i_model = InceptionV3(weights= 'imagenet', include_top=False, input_shape=(299, 299, 3))
for layer in i_model.layers:
    layer.trainable = False

model = Sequential()
model.add(i_model)
model.add(GlobalAveragePooling2D())
model.add(Dense(256))
model.add(Dropout(0.35))
model.add(Dense(15, activation = 'softmax'))
model.summary()

model.compile(loss="categorical_crossentropy", optimizer=keras.optimizers.Adam(learning_rate=0.0001), metrics=["accuracy"])

history = model.fit(
    train_generator,
    steps_per_epoch = train_generator.n//train_generator.batch_size,
    validation_data = train_generator,
    validation_steps = valid_generator.n//valid_generator.batch_size,
    epochs = 25)

score = model.evaluate_generator(valid_generator)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

predict=model.predict_generator(test_generator, steps = len(test_generator.filenames))

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(25)

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()